[[snippets]]
  description = "\\q"
  command = "pet list"
  output = ""

[[snippets]]
  description = "check network connection by pinging google.com"
  command = "ping google.com"
  tag = ["network"]
  output = ""

[[snippets]]
  description = "imap sync with mu | flags: (V)erbose, pu(L)l, e(X)punge deleted messages, operate on (a)ll defined channels"
  command = "mbsync -VLXa"
  tag = ["mail", "mu4e", "imap"]
  output = ""

[[snippets]]
  description = "visidata | CLI tool for tabular data"
  command = "vd"
  output = ""
